IF
	Global("pxd101diag","PXD101",2)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@11032)
		Wait(1)
		DisplayStringHead(Myself,@11038)
		SetGlobal("pxd101diag","PXD101",3)
END

IF
	!GlobalTimerNotExpired("TrueSeeing","LOCALS")
	Detect(NearestEnemyOf(Myself))
	OR(12)
		StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
		StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_INVISIBLE)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_INVISIBLE)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_INVISIBLE)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		SetGlobalTimer("TrueSeeing","LOCALS",TEN_ROUNDS)
		SpellNoDec(Myself,INQUIS_TRUE_SIGHT)
		Continue()
END

IF
	!GlobalTimerNotExpired("Dispel","LOCALS")
	OR(4)
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),INQUIS_DISPEL_MAGIC)
		SetGlobal("pxd101pal","GLOBAL",1)
		SetGlobalTimer("Dispel","LOCALS",FOUR_ROUNDS)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(PALADIN_SUMMON_DEVA)
THEN
	RESPONSE #100
		Spell(Myself,PALADIN_SUMMON_DEVA)
END

IF
	See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
THEN
	RESPONSE #100
		Attack(NearestEnemyOf(Myself))
END

IF
	See(NearestEnemyOfType([0.0.0.BARD_ALL]))
THEN
	RESPONSE #100
		Attack(NearestEnemyOf(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	Range(NearestEnemyOf(Myself),4)
	HaveSpell(WARRIOR_GREATER_WHIRLWIND)
THEN
	RESPONSE #100
		Spell(Myself,WARRIOR_GREATER_WHIRLWIND)
		AttackReevaluate(NearestEnemyOf(Myself),45)
END

IF
	See(NearestEnemyOf(Myself))
	Range(NearestEnemyOf(Myself),4)
	HaveSpell(WARRIOR_WHIRLWIND)
THEN
	RESPONSE #100
		Spell(Myself,WARRIOR_WHIRLWIND)
		AttackReevaluate(NearestEnemyOf(Myself),45)
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Attack(NearestEnemyOf(Myself))
END
