IF
	Die()
THEN
	RESPONSE #100
		SetGlobal("pxd101dead","GLOBAL",1)
END

IF
	Global("pxd101b","LOCALS",1)
THEN
	RESPONSE #100
		ApplySpell(Myself,CLERIC_MAGIC_RESISTANCE)
		ApplySpell(Myself,CLERIC_FREE_ACTION)
		ApplySpell(Myself,CLERIC_REGENERATE)
		SetGlobal("pxd101b","LOCALS",2)
END

IF
	Global("pxd101skin","LOCALS",0)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@11025)
		ApplySpell(Myself,CLERIC_IRONSKIN)
		SetGlobal("pxd101skin","LOCALS",1)
END

IF
	HPPercentLT(Myself,40)
	HaveSpell(CLERIC_HEAL)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_HEAL)
END
		
IF
	See(NearestEnemyOf(Myself))
	HaveSpell(NPC_BLADE_BARRIER)
	!GlobalTimerNotExpired("Barrier","LOCALS")
THEN
	RESPONSE #100
		Spell(Myself,NPC_BLADE_BARRIER)
		SetGlobalTimer("Barrier","LOCALS",TEN_ROUNDS)
		Continue()
END

IF
	HPPercentLT(Myself,40)
	HaveSpell(CLERIC_HEAL)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_HEAL)
END


IF
	CheckStat(Myself,1,SANCTUARY)
	HPPercentGT(Myself,20)
	!CheckSpellState(Myself,ARMOR_OF_FAITH)
	HaveSpell(CLERIC_ARMOR_OF_FAITH)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_ARMOR_OF_FAITH)
END

IF
	CheckStat(Myself,1,SANCTUARY)
	HPPercentLT(Myself,70)
	Global("pxd101tome","LOCALS",0)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@11025)
		ApplySpell(Myself,WARRIOR_HARDINESS)
		SetGlobal("pxd101tome","LOCALS",1)
END

IF
	HPPercentLT(Myself,40)
	HaveSpell(CLERIC_HEAL)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_HEAL)
END

IF
	CheckStat(Myself,1,SANCTUARY)
	Global("pxd101deva","LOCALS",0)
	HaveSpell(CLERIC_SUMMON_FALLEN_DEVA)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_SUMMON_FALLEN_DEVA)
		Wait(2)
		DisplayStringHead(Myself,@11027)
		SetGlobal("pxd101deva","LOCALS",1)
END

IF
	CheckStat(Myself,1,SANCTUARY)
	Global("pxd101deva","LOCALS",1)
	HaveSpell(CLERIC_SUMMON_FALLEN_DEVA)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_SUMMON_FALLEN_DEVA)
END

IF
	CheckStat(Myself,1,SANCTUARY)
	Global("pxd101devin","LOCALS",1)
	HaveSpell(CLERIC_REGENERATE)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_REGENERATE)
END

IF
	CheckStat(Myself,1,SANCTUARY)
	Global("pxd101devin","LOCALS",1)
	HaveSpell(CLERIC_MAGIC_RESISTANCE)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_MAGIC_RESISTANCE)
END

IF
	HPPercentLT(Myself,40)
	HaveSpell(CLERIC_HEAL)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_HEAL)
END

IF
	HPPercentLT(Myself,40)
	Global("pxd101devin","LOCALS",0)
	!HaveSpell(CLERIC_HEAL)
THEN
	RESPONSE #100
		ReallyForceSpell(Myself,CLERIC_SANCTUARY)
		DisplayStringHead(Myself,111655)
		ReallyForceSpell(Myself,HOLY_LIGHT_FROM_ABOVE)
		ReallyForceSpellPointRES("px101bn",[601.751])
		ReallyForceSpellPointRES("px101be",[565.924])
		ReallyForceSpellPointRES("px101bb",[1086.928])
		ReallyForceSpellPointRES("px101bp",[693.922])
		ReallyForceSpellPointRES("px101bv",[884.937]) 
		ReallyForceSpellPointRES("px101bg",[808.776])
		ReallyForceSpellPointRES("px101bm",[1018.779])
		ReallyForceSpellPointRES("px101ba",[584.938])
		DestroyItem("imoenhp1")
		ReallyForceSpellRES("pxd101b1",Myself)
		SetGlobal("pxd101tome","LOCALS",0)
		SetGlobal("pxd101skin","LOCALS",0)
		SetGlobal("pxd101devin","LOCALS",1)
END

IF
	Global("pxd101devin","LOCALS",1)
	HaveSpell(CLERIC_FINGER_OF_DEATH)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
THEN
	RESPONSE #100	
	Spell(LastSeenBy(Myself),CLERIC_FINGER_OF_DEATH)
END	

IF
	HPPercentLT(Myself,40)
	HaveSpell(CLERIC_HEAL)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_HEAL)
END

IF
	HaveSpell(CLERIC_AERIAL_SERVANT)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_AERIAL_SERVANT)
END

IF
	!GlobalTimerNotExpired("TrueSeeing","LOCALS")
	Detect(NearestEnemyOf(Myself))
	OR(12)
		StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
		StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_INVISIBLE)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_INVISIBLE)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_INVISIBLE)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		SetGlobalTimer("TrueSeeing","LOCALS",TEN_ROUNDS)
		SpellNoDec(Myself,CLERIC_TRUE_SIGHT)
		Continue()
END

IF
	Global("pxd101devin","LOCALS",1)
	HaveSpell(CLERIC_DEFENSIVE_HARMONY)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100	
	Spell(Myself,CLERIC_DEFENSIVE_HARMONY)
END	

IF
	HPPercentLT(Myself,40)
	HaveSpell(CLERIC_HEAL)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_HEAL)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(CLERIC_SYMBOL_STUN)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_SYMBOL_STUN)
END

IF
	HPPercentLT(Myself,40)
	HaveSpell(CLERIC_HEAL)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_HEAL)
END

IF
	HaveSpell(CLERIC_SILENCE_15_FOOT)
	OR(3)
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.THIEF_ALL]))
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)
END

IF
	HPPercentLT(Myself,40)
	HaveSpell(CLERIC_HEAL)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_HEAL)
END

IF
	HaveSpell(CLERIC_POISON)
	See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_POISON)
END

IF
	HPPercentLT(Myself,40)
	HaveSpell(CLERIC_HEAL)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_HEAL)
END

IF
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	See(NearestEnemyOfType([0.0.0.FIGHTER_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	HPPercentLT(Myself,40)
	HaveSpell(CLERIC_HEAL)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_HEAL)
END

IF
	HaveSpell(CLERIC_FLAME_STRIKE)
	OR(3)
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.THIEF_ALL]))
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)
END

IF
	HPPercentLT(Myself,40)
	HaveSpell(CLERIC_HEAL)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_HEAL)
END

IF
	HaveSpell(CLERIC_AERIAL_SERVANT)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_AERIAL_SERVANT)
END

IF
	HPPercentLT(Myself,40)
	HaveSpell(CLERIC_HEAL)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_HEAL)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(CLERIC_ANIMATE_DEAD)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_ANIMATE_DEAD)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(ENEMY_CLERIC_HARM)
	HPGT(LastSeenBy(Myself),150)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),ENEMY_CLERIC_HARM)
END

IF
	See(NearestEnemyOf(Myself))
	HPLT(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	HPPercentLT(Myself,40)
	HaveSpell(CLERIC_HEAL)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_HEAL)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(ENEMY_CLERIC_SLAY_LIVING)
	!CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),ENEMY_CLERIC_SLAY_LIVING)
END

IF
	HPPercentLT(Myself,40)
	HaveSpell(CLERIC_HEAL)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_HEAL)
END

IF
	CheckStatLT(Myself,19,STR)
	HaveSpell(CLERIC_HOLY_POWER)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_HOLY_POWER)
END


IF
	HaveSpell(CLERIC_RIGHTEOUS_MAGIC)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_RIGHTEOUS_MAGIC)
END


IF
	See(NearestEnemyOf(Myself))
	Range(NearestEnemyOf(Myself),7)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(NearestEnemyOf(Myself),30)
END