IF
	AttackedBy([ANYONE],DEFAULT)
THEN
    RESPONSE #100
        AttackReevaluate(LastAttackerOf(Myself),30)
END

IF
    Global("pxdtelim","GLOBAL",2)
	See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
THEN
    RESPONSE #100
        AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Global("pxdtelim","GLOBAL",2)
    See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
THEN
    RESPONSE #100
        AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Global("pxdtelim","GLOBAL",2)
    See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
THEN
    RESPONSE #100
        AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Global("pxdtelim","GLOBAL",2)
    See(NearestEnemyOfType([0.0.0.BARD_ALL]))
THEN
    RESPONSE #100
        AttackReevaluate(LastSeenBy(Myself),30)
END

IF
    Global("pxdtelim","GLOBAL",2)
	See(NearestEnemyOfType([0.0.0.THIEF_ALL]))
THEN
    RESPONSE #100
        AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Global("pxdtelim","GLOBAL",2)
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        AttackReevaluate(NearestEnemyOf(Myself),30)
END