
IF
	See(NearestEnemyOf(Myself))
	GlobalLT("telim5","LOCALS",6)
	!GlobalTimerNotExpired("casting","LOCALS")
	OR(5)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
		CheckSpellState(LastSeenBy(Myself),MANTLE)
		CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
		CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
THEN
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_BREACH) 
		IncrementGlobal("telim5","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
END

IF
	Global("teldoble","LOCALS",0)
    See(NearestEnemyOf(Myself))
    !StateCheck(Myself,STATE_INVISIBLE)
    !GlobalTimerNotExpired("casting","LOCALS")
    GlobalLT("telim6","LOCALS",4)
THEN
    RESPONSE #100
        ReallyForceSpell(Myself,WIZARD_MISLEAD)
        IncrementGlobal("telim6","LOCALS",1)
		SetGlobal("teldoble","LOCALS",1)
        SetGlobalTimer("casting","LOCALS",ONE_ROUND)
END

IF
    See(NearestEnemyOf(Myself))
    CheckStat(Myself,0,IMPROVEDHASTE)
    !GlobalTimerNotExpired("casting","LOCALS")
    GlobalLT("telim6","LOCALS",4)
THEN
    RESPONSE #100
        ReallyForceSpell(Myself,WIZARD_IMPROVED_HASTE)
        IncrementGlobal("telim6","LOCALS",1)
        SetGlobalTimer("casting","LOCALS",ONE_ROUND)
END

IF
    Detect(NearestEnemyOf(Myself))
    !StateCheck(Myself,STATE_INVISIBLE)
    !GlobalTimerNotExpired("casting","LOCALS")
    GlobalLT("telim6","LOCALS",7)
THEN
    RESPONSE #100
        ReallyForceSpell(Myself,WIZARD_MISLEAD)
        IncrementGlobal("telim6","LOCALS",1)
        SetGlobalTimer("casting","LOCALS",ONE_ROUND)
END

IF
    Detect(NearestEnemyOf(Myself))
    CheckStat(Myself,0,IMPROVEDHASTE)
    !GlobalTimerNotExpired("casting","LOCALS")
    GlobalLT("telim6","LOCALS",7)
THEN
    RESPONSE #100
        ReallyForceSpell(Myself,WIZARD_IMPROVED_HASTE)
        IncrementGlobal("telim6","LOCALS",1)
        SetGlobalTimer("casting","LOCALS",ONE_ROUND)
END

IF
	Global("px105simpurg","LOCALS",0)
	!GlobalTimerNotExpired("casting","LOCALS")
	Detect(NearestEnemyOf(Myself))
	GlobalLT("telim6","LOCALS",4)
	OR(12)
		StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
		StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_INVISIBLE)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_INVISIBLE)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_INVISIBLE)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
		IncrementGlobal("telim6","LOCALS",1)
		SetGlobal("px105simpurg","LOCALS",1)
		ReallyForceSpell(Myself,WIZARD_TRUE_SIGHT)
END

IF
	See(NearestEnemyOf(Myself))
	GlobalLT("telim8","LOCALS",3)
	!GlobalTimerNotExpired("casting","LOCALS")
THEN
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING) 
		IncrementGlobal("telim8","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING) 
		IncrementGlobal("telim8","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING) 
		IncrementGlobal("telim8","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING) 
		IncrementGlobal("telim8","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_SYMBOL_STUN) 
		IncrementGlobal("telim8","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_MAZE) 
		IncrementGlobal("telim8","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
END

IF
	See(NearestEnemyOf(Myself))
	GlobalLT("telim7","LOCALS",4)
	!GlobalTimerNotExpired("casting","LOCALS")
THEN
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_MORDENKAINENS_SWORD) 
		IncrementGlobal("telim7","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_POWER_WORD_STUN) 
		IncrementGlobal("telim7","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
	RESPONSE #100
		ReallyForceSpellRES("pxdproja",NearestEnemyOf(Myself))
		IncrementGlobal("telim7","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
	RESPONSE #100
		ReallyForceSpellRES("pxdproja",NearestEnemyOf(Myself))
		IncrementGlobal("telim7","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
END

IF
	See(NearestEnemyOf(Myself))
	GlobalLT("telim5","LOCALS",6)
	!GlobalTimerNotExpired("casting","LOCALS")
THEN
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_CHAOS) 
		IncrementGlobal("telim5","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_DOMINATION) 
		IncrementGlobal("telim5","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_FEEBLEMIND) 
		IncrementGlobal("telim5","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
END

IF
	See(NearestEnemyOf(Myself))
	GlobalLT("telim4","LOCALS",6)
	!GlobalTimerNotExpired("casting","LOCALS")
THEN
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_POLYMORPH_OTHER) 
		IncrementGlobal("telim4","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_GREATER_MALISON) 
		IncrementGlobal("telim4","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
	RESPONSE #100
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED) 
		IncrementGlobal("telim4","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
	RESPONSE #100
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE) 
		IncrementGlobal("telim4","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
END

IF
	See(NearestEnemyOf(Myself))
	GlobalLT("telim3","LOCALS",6)
	!GlobalTimerNotExpired("casting","LOCALS")
THEN
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_FLAME_ARROW) 
		IncrementGlobal("telim3","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_SLOW) 
		IncrementGlobal("telim3","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_VAMPIRIC_TOUCH) 
		IncrementGlobal("telim3","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_VAMPIRIC_TOUCH) 
		IncrementGlobal("telim3","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
END

IF
	See(NearestEnemyOf(Myself))
	GlobalLT("telim2","LOCALS",6)
	!GlobalTimerNotExpired("casting","LOCALS")
THEN
	RESPONSE #100
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE) 
		IncrementGlobal("telim2","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_MELF_ACID_ARROW) 
		IncrementGlobal("telim2","LOCALS",1)
		SetGlobalTimer("casting","LOCALS",ONE_ROUND)
END