IF
	OnCreation()
	Global("px101start","PXD101",0)
THEN
	RESPONSE #100
		Explore()
		StartTimer(6,30)
		SetGlobal("px101start","PXD101",1)
		ActionOverride("pxd101b",StartDialogueNoSet([PC]))
END

IF
	OnCreation()
	Global("px101start","PXD101",1)
THEN
	RESPONSE #100
		StartTimer(6,30)
END

IF
   TimerExpired(6)
   RandomNum(10,1)
THEN
    RESPONSE #100
        ReallyForceSpellPointRES("Pxd1101",[865.801])
		CreateCreature("pxd101sp",[650.840],S)
        StartTimer(6,18)
    RESPONSE #100
        ReallyForceSpellPointRES("Pxd1101",[865.801])
		CreateCreature("pxd101sp",[789.922],S)
        StartTimer(6,24)
	RESPONSE #100
        ReallyForceSpellPointRES("Pxd1101",[865.801])
		CreateCreature("pxd101sp",[1008.915],S)
        StartTimer(6,30)
    RESPONSE #100
        ReallyForceSpellPointRES("Pxd1101",[865.801])
		CreateCreature("pxd101sp",[828.823],S)
        StartTimer(6,36)
    RESPONSE #100
        ReallyForceSpellPointRES("Pxd1101",[865.801])
		CreateCreature("pxd101sp",[854.722],S)
        StartTimer(6,42)
    RESPONSE #100
        ReallyForceSpellPointRES("Pxd1101",[865.801])
		CreateCreature("pxd101sp",[1101.834],S)
        StartTimer(6,48)		
END

IF
	TimerExpired(6)
THEN
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[865.801])
		StartTimer(6,18)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[865.801])
		StartTimer(6,24)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[865.801])
		StartTimer(6,30)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[865.801])
		StartTimer(6,36)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[865.801])
		StartTimer(6,42)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[865.801])
		StartTimer(6,48)
END


IF
	Global("pxd101dead","GLOBAL",1)
THEN
	RESPONSE #100
		Wait(8)
		CreateVisualEffect("pxl2xspv",[796.734])
		Wait(2)
		CreateCreature("pxdnerul",[796.734],S)
		SetGlobal("pxd101dead","GLOBAL",2)
END

IF
    Global("px100wn","GLOBAL",1)
	Global("pxdgolem","GLOBAL",1)
THEN
    RESPONSE #100
    SetGlobal("px100wn","GLOBAL",2)
    ActionOverride(Player1,LeaveAreaLUA("AR0500","",[2387.1252],NNW))
    ActionOverride(Player2,LeaveAreaLUA("AR0500","",[2428.1222],NNW))
    ActionOverride(Player3,LeaveAreaLUA("AR0500","",[2477.1247],NNW))
    ActionOverride(Player4,LeaveAreaLUA("AR0500","",[2437.1281],NNW))
    ActionOverride(Player5,LeaveAreaLUA("AR0500","",[2484.1249],NNW))
    ActionOverride(Player6,LeaveAreaLUA("AR0500","",[2520.1270],NNW))
END


IF
	Global("px100wn","GLOBAL",1)
	Global("pxdgolem","GLOBAL",2)
THEN
	RESPONSE #100
	SetGlobal("px100wn","GLOBAL",2)
	ActionOverride(Player1,LeaveAreaLUA("AR3001","",[2253.1042],NE))
	ActionOverride(Player2,LeaveAreaLUA("AR3001","",[2280.1074],NE))
	ActionOverride(Player3,LeaveAreaLUA("AR3001","",[2238.1108],NE))
	ActionOverride(Player4,LeaveAreaLUA("AR3001","",[2202.1075],NE))
	ActionOverride(Player5,LeaveAreaLUA("AR3001","",[2170.1095],NE))
	ActionOverride(Player6,LeaveAreaLUA("AR3001","",[2191.1132],NE))
END


IF
	Global("px100wn","GLOBAL",1)
	Global("pxdgolem","GLOBAL",3)
THEN
	RESPONSE #100
	SetGlobal("px100wn","GLOBAL",2)
	ActionOverride(Player1,LeaveAreaLUA("AR5500","",[3662.1637],N))
	ActionOverride(Player2,LeaveAreaLUA("AR5500","",[3704.1627],N))
	ActionOverride(Player3,LeaveAreaLUA("AR5500","",[3702.1660],N))
	ActionOverride(Player4,LeaveAreaLUA("AR5500","",[3659.1667],N))
	ActionOverride(Player5,LeaveAreaLUA("AR5500","",[3660.1705],N))
	ActionOverride(Player6,LeaveAreaLUA("AR5500","",[3704.1700],N))
END