IF
    OnCreation()
	Global("px190start","PXD190",0)
THEN
    RESPONSE #100
        Explore()
        ReallyForceSpellPointRES("Pxd1901",[2558.1900])
        StartTimer(6,6)
        Wait(2)
        CreateCreature("pxd190t",[2558.1900],S)
        ActionOverride("pxd190t",StartDialogueNoSet([PC]))
		SetGlobal("px190start","PXD190",0)
END

IF
    OnCreation()
	Global("px190start","PXD190",1)
THEN
    RESPONSE #100
        ReallyForceSpellPointRES("Pxd1901",[2558.1900])
        StartTimer(6,6)
END

IF
    TimerExpired(6)
	RandomNum(6,1)
THEN
    RESPONSE #100
        ReallyForceSpellPointRES("Pxd1901",[2558.1900])
        CreateCreature("pxd190ac",[2558.1900],S)
        DisplayStringNoName(Myself,106026)
        StartTimer(6,6)
        IncrementGlobal("pxd190","PXD190",1)
END

IF
    TimerExpired(6)
THEN
    RESPONSE #100
        ReallyForceSpellPointRES("Pxd1901",[2558.1900])
        StartTimer(6,6)
        IncrementGlobal("pxd190","PXD190",1)
END

IF
    GlobalGT("pxd190","PXD190",99)
    Global("PXD190boss","PXD190",0)
THEN
    RESPONSE #100
        SetGlobal("PXD190boss","PXD190",1)
        GiveItemCreate("pxd190r",Player1,1,0,0)
        CreateCreature("pxd190t",[2558.1900],S)
        ActionOverride("pxd190t",StartDialogueNoSet([PC]))
END

IF
    Global("px190b1","PXD190",1)
    Delay(18)
THEN
    RESPONSE #100
        CreateCreature("pxd190b",[2558.1900],S)
        SetGlobal("px190b1","PXD190",0)
END

IF
    Global("px190b2","PXD190",1)
    Delay(18)
THEN
    RESPONSE #100
        CreateCreature("pxd190b2",[2548.1910],S)
        SetGlobal("px190b2","PXD190",0)
END

IF
    Global("px190b3","PXD190",1)
    Delay(18)
THEN
    RESPONSE #100
        CreateCreature("pxd190b3",[2568.1890],S)
        SetGlobal("px190b3","p190",0)
END

IF
    Global("px190wn","GLOBAL",1)
	Global("pxdgolem","GLOBAL",1)
THEN
    RESPONSE #100
    SetGlobal("px190wn","GLOBAL",2)
    ActionOverride(Player1,LeaveAreaLUA("AR0500","",[2387.1252],NNW))
    ActionOverride(Player2,LeaveAreaLUA("AR0500","",[2428.1222],NNW))
    ActionOverride(Player3,LeaveAreaLUA("AR0500","",[2477.1247],NNW))
    ActionOverride(Player4,LeaveAreaLUA("AR0500","",[2437.1281],NNW))
    ActionOverride(Player5,LeaveAreaLUA("AR0500","",[2484.1249],NNW))
    ActionOverride(Player6,LeaveAreaLUA("AR0500","",[2520.1270],NNW))
END


IF
	Global("px190wn","GLOBAL",1)
	Global("pxdgolem","GLOBAL",2)
THEN
	RESPONSE #100
	SetGlobal("px190wn","GLOBAL",2)
	ActionOverride(Player1,LeaveAreaLUA("AR3001","",[2253.1042],NE))
	ActionOverride(Player2,LeaveAreaLUA("AR3001","",[2280.1074],NE))
	ActionOverride(Player3,LeaveAreaLUA("AR3001","",[2238.1108],NE))
	ActionOverride(Player4,LeaveAreaLUA("AR3001","",[2202.1075],NE))
	ActionOverride(Player5,LeaveAreaLUA("AR3001","",[2170.1095],NE))
	ActionOverride(Player6,LeaveAreaLUA("AR3001","",[2191.1132],NE))
END


IF
	Global("px190wn","GLOBAL",1)
	Global("pxdgolem","GLOBAL",3)
THEN
	RESPONSE #100
	SetGlobal("px190wn","GLOBAL",2)
	ActionOverride(Player1,LeaveAreaLUA("AR5500","",[3662.1637],N))
	ActionOverride(Player2,LeaveAreaLUA("AR5500","",[3704.1627],N))
	ActionOverride(Player3,LeaveAreaLUA("AR5500","",[3702.1660],N))
	ActionOverride(Player4,LeaveAreaLUA("AR5500","",[3659.1667],N))
	ActionOverride(Player5,LeaveAreaLUA("AR5500","",[3660.1705],N))
	ActionOverride(Player6,LeaveAreaLUA("AR5500","",[3704.1700],N))
END