IF
    OnCreation()
THEN
    RESPONSE #100
        ReallyForceSpellPointRES("Pxd1001",[2627.1141])
        StartTimer(6,6)
END

IF
    TimerExpired(6)
THEN
    RESPONSE #100
        ReallyForceSpellPointRES("Pxd1001",[2627.1141])
        StartTimer(6,6)			
END

IF
    Global("px100wn","GLOBAL",1)
THEN
    RESPONSE #100
    SetGlobal("px100wn","GLOBAL",2)
    ActionOverride(Player1,LeaveAreaLUA("AR0500","",[2387.1252],NNW))
    ActionOverride(Player2,LeaveAreaLUA("AR0500","",[2428.1222],NNW))
    ActionOverride(Player3,LeaveAreaLUA("AR0500","",[2477.1247],NNW))
    ActionOverride(Player4,LeaveAreaLUA("AR0500","",[2437.1281],NNW))
    ActionOverride(Player5,LeaveAreaLUA("AR0500","",[2484.1249],NNW))
    ActionOverride(Player6,LeaveAreaLUA("AR0500","",[2520.1270],NNW))
END