IF
	OnCreation()
	Global("pxdport","PXD201",1)
	Global("pxdsecret2","PXD201",1)
	Global("px290wn","GLOBAL",0)
THEN
	RESPONSE #100
		StartTimer(201,2)
		CreateVisualEffect("pxd201sv",[3456.411])
		TriggerActivation("secret2",TRUE)
END

/*
IF
	GlobalGT("px290wn","GLOBAL",0)
THEN
	RESPONSE #100
		TriggerActivation("pxd201sv",FALSE)
		TriggerActivation("secret2",FALSE)
END
*/

IF
	OnCreation()
	Global("pxdport","PXD201",0)
THEN
	RESPONSE #100
		CreateCreature("pxd201ng",[741.1185],S)
		CreateCreature("pxd201pt",[468.1497],S)
		StartTimer(201,12)
		SetGlobal("pxdport","PXD201",1)
END

IF
	OnCreation()
	Global("pxdport","PXD201",1)
THEN
	RESPONSE #100
		StartTimer(201,12)
END

IF
	Global("pxdhour1","GLOBAL",2)
	Global("pxdhour2","GLOBAL",2)
	Global("pxdhour3","GLOBAL",2)
	Global("pxdsecret2","PXD201",0)
THEN
	RESPONSE #100
		CreateVisualEffect("pxd201sv",[3456.411])
		SetGlobal("pxdsecret2","PXD201",1)
		TriggerActivation(" secret2",TRUE)
		AddMapNote([3455.347],@20116)
END

IF
	!Dead("pxd201b")
	TimerExpired(201)
	RandomNum(10,1)
	!Exists("pxd201pt")
THEN
	RESPONSE #100
		CreateCreature("pxd201ng",[741.1185],S)
		CreateCreature("pxd201pt",[468.1497],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[1601.1515],S)
		CreateCreature("pxd201pt",[468.1497],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[791.1948],S)
		CreateCreature("pxd201pt",[468.1497],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[1808.2384],S)
		CreateCreature("pxd201pt",[468.1497],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[2174.3037],S)
		CreateCreature("pxd201pt",[468.1497],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[2836.2800],S)
		CreateCreature("pxd201pt",[468.1497],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[2428.2140],S)
		CreateCreature("pxd201pt",[468.1497],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[3290.2471],S)
		CreateCreature("pxd201pt",[468.1497],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[3557.1980],S)
		CreateCreature("pxd201pt",[468.1497],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[2965.1700],S)
		CreateCreature("pxd201pt",[468.1497],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[2331.1308],S)
		CreateCreature("pxd201pt",[468.1497],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[3373.1317],S)
		CreateCreature("pxd201pt",[468.1497],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[3465.599],S)
		CreateCreature("pxd201pt",[468.1497],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[4002.2940],S)
		CreateCreature("pxd201pt",[468.1497],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[2996.2233],S)
		CreateCreature("pxd201pt",[468.1497],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[1865.2871],S)
		CreateCreature("pxd201pt",[468.1497],S)
		StartTimer(201,12)
END

IF
	!Dead("pxd201b")
	TimerExpired(201)
THEN
	RESPONSE #100
		CreateCreature("pxd201ng",[741.1185],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[1601.1515],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[791.1948],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[1808.2384],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[2174.3037],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[2836.2800],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[2428.2140],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[3290.2471],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[3557.1980],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[2965.1700],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[2331.1308],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[3373.1317],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[3465.599],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[4002.2940],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[2996.2233],S)
		StartTimer(201,12)
	RESPONSE #100
		CreateCreature("pxd201ng",[1865.2871],S)
		StartTimer(201,12)
END

IF
	Dead("pxd201b")
	TimerExpired(201)
	RandomNum(10,1)
	!Exists("pxd201pt")
THEN
	RESPONSE #100
		CreateCreature("pxd201pt",[468.1497],S)
		StartTimer(201,12)
END

IF
	Dead("pxd201b")
	TimerExpired(201)
THEN
	RESPONSE #100
		StartTimer(201,12)
END

IF
    Global("px201wn","GLOBAL",1)
	Global("pxdgolem","GLOBAL",1)
THEN
    RESPONSE #100
    SetGlobal("px201wn","GLOBAL",2)
    ActionOverride(Player1,LeaveAreaLUA("AR0500","",[2387.1252],NNW))
    ActionOverride(Player2,LeaveAreaLUA("AR0500","",[2428.1222],NNW))
    ActionOverride(Player3,LeaveAreaLUA("AR0500","",[2477.1247],NNW))
    ActionOverride(Player4,LeaveAreaLUA("AR0500","",[2437.1281],NNW))
    ActionOverride(Player5,LeaveAreaLUA("AR0500","",[2484.1249],NNW))
    ActionOverride(Player6,LeaveAreaLUA("AR0500","",[2520.1270],NNW))
END


IF
	Global("px201wn","GLOBAL",1)
	Global("pxdgolem","GLOBAL",2)
THEN
	RESPONSE #100
	SetGlobal("px201wn","GLOBAL",2)
	ActionOverride(Player1,LeaveAreaLUA("AR3001","",[2253.1042],NE))
	ActionOverride(Player2,LeaveAreaLUA("AR3001","",[2280.1074],NE))
	ActionOverride(Player3,LeaveAreaLUA("AR3001","",[2238.1108],NE))
	ActionOverride(Player4,LeaveAreaLUA("AR3001","",[2202.1075],NE))
	ActionOverride(Player5,LeaveAreaLUA("AR3001","",[2170.1095],NE))
	ActionOverride(Player6,LeaveAreaLUA("AR3001","",[2191.1132],NE))
END


IF
	Global("px201wn","GLOBAL",1)
	Global("pxdgolem","GLOBAL",3)
THEN
	RESPONSE #100
	SetGlobal("px201wn","GLOBAL",2)
	ActionOverride(Player1,LeaveAreaLUA("AR5500","",[3662.1637],N))
	ActionOverride(Player2,LeaveAreaLUA("AR5500","",[3704.1627],N))
	ActionOverride(Player3,LeaveAreaLUA("AR5500","",[3702.1660],N))
	ActionOverride(Player4,LeaveAreaLUA("AR5500","",[3659.1667],N))
	ActionOverride(Player5,LeaveAreaLUA("AR5500","",[3660.1705],N))
	ActionOverride(Player6,LeaveAreaLUA("AR5500","",[3704.1700],N))
END