IF
	OnCreation()
THEN
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd7081",[3677.1619])
		ReallyForceSpellPointRES("Pxd7081",[2530.1298])
		StartTimer(1,1)
		IncrementGlobal("pxd708","pxd708",1)
END

IF
	Global("px501wn","GLOBAL",0)
	Global("px501hammer","GLOBAL",0)
	GlobalGT("pxd708","pxd708",29)
THEN
	RESPONSE #100
		CreateCreature("pxd708sp",[2437.728],S)
		SetGlobal("pxd708","pxd708",0)
		StartTimer(1,1)
END

IF
	Global("px501wn","GLOBAL",0)
	Global("px501hammer","GLOBAL",1)
	GlobalGT("pxd708","pxd708",17)
THEN
	RESPONSE #100
		CreateCreature("pxd708sp",[2437.728],S)
		SetGlobal("pxd708","pxd708",0)
		StartTimer(1,1)
END

IF
	TimerExpired(1)
THEN
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd7081",[3677.1619])
		ReallyForceSpellPointRES("Pxd7081",[2530.1298])
		IncrementGlobal("pxd708","pxd708",1)
		StartTimer(1,1)
END

IF
    Global("px708wn","GLOBAL",1)
	Global("pxdgolem","GLOBAL",1)
THEN
    RESPONSE #100
    SetGlobal("px708wn","GLOBAL",2)
    ActionOverride(Player1,LeaveAreaLUA("AR0500","",[2387.1252],NNW))
    ActionOverride(Player2,LeaveAreaLUA("AR0500","",[2428.1222],NNW))
    ActionOverride(Player3,LeaveAreaLUA("AR0500","",[2477.1247],NNW))
    ActionOverride(Player4,LeaveAreaLUA("AR0500","",[2437.1281],NNW))
    ActionOverride(Player5,LeaveAreaLUA("AR0500","",[2484.1249],NNW))
    ActionOverride(Player6,LeaveAreaLUA("AR0500","",[2520.1270],NNW))
END


IF
	Global("px708wn","GLOBAL",1)
	Global("pxdgolem","GLOBAL",2)
THEN
	RESPONSE #100
	SetGlobal("px708wn","GLOBAL",2)
	ActionOverride(Player1,LeaveAreaLUA("AR3001","",[2253.1042],NE))
	ActionOverride(Player2,LeaveAreaLUA("AR3001","",[2280.1074],NE))
	ActionOverride(Player3,LeaveAreaLUA("AR3001","",[2238.1108],NE))
	ActionOverride(Player4,LeaveAreaLUA("AR3001","",[2202.1075],NE))
	ActionOverride(Player5,LeaveAreaLUA("AR3001","",[2170.1095],NE))
	ActionOverride(Player6,LeaveAreaLUA("AR3001","",[2191.1132],NE))
END


IF
	Global("px708wn","GLOBAL",1)
	Global("pxdgolem","GLOBAL",3)
THEN
	RESPONSE #100
	SetGlobal("px708wn","GLOBAL",2)
	ActionOverride(Player1,LeaveAreaLUA("AR5500","",[3662.1637],N))
	ActionOverride(Player2,LeaveAreaLUA("AR5500","",[3704.1627],N))
	ActionOverride(Player3,LeaveAreaLUA("AR5500","",[3702.1660],N))
	ActionOverride(Player4,LeaveAreaLUA("AR5500","",[3659.1667],N))
	ActionOverride(Player5,LeaveAreaLUA("AR5500","",[3660.1705],N))
	ActionOverride(Player6,LeaveAreaLUA("AR5500","",[3704.1700],N))
END