IF
	GlobalGT("pxdvoid","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("pxdvoid","GLOBAL",0)
		ClearAllActions()
		CreateVisualEffectObject("icccmdsi",Player1)
		CreateVisualEffectObject("icccmdsi",Player2)
		CreateVisualEffectObject("icccmdsi",Player3)
		CreateVisualEffectObject("icccmdsi",Player4)
		CreateVisualEffectObject("icccmdsi",Player5)
		CreateVisualEffectObject("icccmdsi",Player6)
		CreateVisualEffectObject("icccmdsi",Familiar)
		Wait(2)
		RestorePartyLocations()		
END

IF
	PartyHasItem("pxdvoid")  // Portail portable
THEN
	RESPONSE #100
		TriggerActivation("to0109",FALSE)
END

IF
	!PartyHasItem("pxdvoid")  // Portail portable
THEN
	RESPONSE #100
		TriggerActivation("to0109",TRUE)
END