IF
	Die()
THEN
    RESPONSE #100	
		ReallyForceSpellDeadRES("pxl2jcvn",Myself)
		Wait(1)
		DestroySelf()
END

IF
	Global("pxd200hp","LOCALS",0)
	See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("pxd2003","LOCALS")
THEN
    RESPONSE #100
		PlaySound("COW01")
        ReallyForceSpellRES("px2903v",NearestEnemyOf(Myself))
        SetGlobalTimer("pxd2003","LOCALS",6)
END

IF
	Global("pxd200hp","LOCALS",0)
	OR(3)
        HPPercentLT(Myself,100)
        AttackedBy([ANYONE],DEFAULT)
        TookDamage()
THEN
    RESPONSE #100
		SetGlobal("pxd200hp","LOCALS",1)
		SetGlobalTimer("pxd2003","LOCALS",2)
		ReallyForceSpellRES("px2903v",LastAttackerOf(Myself))
END

IF
	Global("pxd200hp","LOCALS",1)
	See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("pxd2003","LOCALS")
THEN
    RESPONSE #100
		PlaySound("COW01")
        ReallyForceSpellRES("px2903v",NearestEnemyOf(Myself))
        SetGlobalTimer("pxd2003","LOCALS",2)
END