IF
	GlobalGT("pxdvoid","GLOBAL",0)
	Global("pxdavert","GLOBAL",1)
THEN
	RESPONSE #100
		ClearAllActions()
		StorePartyLocations()
		CreateVisualEffectObject("icccmdsi",Player1)
		CreateVisualEffectObject("icccmdsi",Player2)
		CreateVisualEffectObject("icccmdsi",Player3)
		CreateVisualEffectObject("icccmdsi",Player4)
		CreateVisualEffectObject("icccmdsi",Player5)
		CreateVisualEffectObject("icccmdsi",Player6)
		CreateVisualEffectObject("icccmdsi",Familiar)
		Wait(2)
		ActionOverride(Player1,LeaveAreaLUA("pxd204","",[1385.892],SEE))
		ActionOverride(Player2,LeaveAreaLUA("pxd204","",[1401.832],NWW))
		ActionOverride(Player3,LeaveAreaLUA("pxd204","",[1464.820],N))
		ActionOverride(Player4,LeaveAreaLUA("pxd204","",[1512.844],NEE))
		ActionOverride(Player5,LeaveAreaLUA("pxd204","",[1511.896],SE))
		ActionOverride(Player6,LeaveAreaLUA("pxd204","",[1446.913],S))
		TakePartyItem("PXDVOID")
		SetGlobal("pxdvoid","GLOBAL",0)
		SetGlobal("pxdavert","GLOBAL",2)
END

IF
	GlobalGT("pxdvoid","GLOBAL",0)
	Global("pxdavert","GLOBAL",2)
THEN
	RESPONSE #100
		ClearAllActions()
		StorePartyLocations()
		CreateVisualEffectObject("icccmdsi",Player1)
		CreateVisualEffectObject("icccmdsi",Player2)
		CreateVisualEffectObject("icccmdsi",Player3)
		CreateVisualEffectObject("icccmdsi",Player4)
		CreateVisualEffectObject("icccmdsi",Player5)
		CreateVisualEffectObject("icccmdsi",Player6)
		CreateVisualEffectObject("icccmdsi",Familiar)
		Wait(2)
		ActionOverride(Player1,LeaveAreaLUA("pxd203","",[970.655],SEE))
		ActionOverride(Player2,LeaveAreaLUA("pxd203","",[917.704],SEE))
		ActionOverride(Player3,LeaveAreaLUA("pxd203","",[829.703],SW))
		ActionOverride(Player4,LeaveAreaLUA("pxd203","",[831.630],NWW))
		ActionOverride(Player5,LeaveAreaLUA("pxd203","",[871.576],NWW))
		ActionOverride(Player6,LeaveAreaLUA("pxd203","",[965.577],NNE))
		TakePartyItem("PXDVOID")
		SetGlobal("pxdvoid","GLOBAL",20)
		SetGlobal("pxdavert","GLOBAL",20)
END

IF
	OnCreation()
	Global("PXD105","PXD105",0)
THEN
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t01",[888.1756],S)  // Tarasque pyrophore
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t02",[888.1756],S)  // Tarasque cryophique
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t03",[888.1756],S)  // Tarasque accélérée
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t05",[888.1756],S)  // Tarasque berserk
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t07",[888.1756],S)  // Tarasque rayonnante
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t10",[888.1756],S)  // Tarasque aveuglante
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t11",[888.1756],S)  // Tarasque du malheur
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t14",[888.1756],S)  // Tarasque épuisante
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t17",[888.1756],S)  // Tarasque venimeuse
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t20",[888.1756],S)  // Tarasque du destin
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t22",[888.1756],S)  // Tarasque de la peste
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t23",[888.1756],S)  // Tarasque du silence
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t28",[888.1756],S)  // Tarasque paralysante
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t31",[888.1756],S)  // Tarasque de Sombrelune
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t35",[888.1756],S)  // Tarasque nécromantique
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t37",[888.1756],S)  // Tarasque chargée
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t39",[888.1756],S)  // Tarasque explosive
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t41",[888.1756],S)  // Tarasque antimagique
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t46",[888.1756],S)  // Tarasque temporelle
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t47",[888.1756],S)  // Tarasque protectrice
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t50",[888.1756],S)  // Tarasque pyro-liée
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t51",[888.1756],S)  // Tarasque du carnage
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t57",[888.1756],S)  // Tarasque maîtresse des mouches
	RESPONSE #100
		SetGlobal("PXD105","PXD105",1)
		CreateCreature("px105t58",[888.1756],S)  // Tarasque hypnotique
END

IF
	Global("PXD105","PXD105",1)
THEN
	RESPONSE #100
		SetGlobal("PXD105","PXD105",2)
		CreateCreature("pxd190b4",[2682.1505],W)
END

IF
    Global("px190b4","PXD105",1)
    Delay(18)
THEN
    RESPONSE #100
       CreateCreature("pxd190b4",[2682.1505],W)
        SetGlobal("px190b4","PXD105",0)
END


IF
    Global("px105wn","GLOBAL",1)
	Global("pxdgolem","GLOBAL",1)
THEN
    RESPONSE #100
    SetGlobal("px105wn","GLOBAL",2)
    ActionOverride(Player1,LeaveAreaLUA("AR0500","",[2387.1252],NNW))
    ActionOverride(Player2,LeaveAreaLUA("AR0500","",[2428.1222],NNW))
    ActionOverride(Player3,LeaveAreaLUA("AR0500","",[2477.1247],NNW))
    ActionOverride(Player4,LeaveAreaLUA("AR0500","",[2437.1281],NNW))
    ActionOverride(Player5,LeaveAreaLUA("AR0500","",[2484.1249],NNW))
    ActionOverride(Player6,LeaveAreaLUA("AR0500","",[2520.1270],NNW))
END

IF
	Global("px105wn","GLOBAL",1)
	Global("pxdgolem","GLOBAL",2)
THEN
	RESPONSE #100
	SetGlobal("px105wn","GLOBAL",2)
	ActionOverride(Player1,LeaveAreaLUA("AR3001","",[2253.1042],NE))
	ActionOverride(Player2,LeaveAreaLUA("AR3001","",[2280.1074],NE))
	ActionOverride(Player3,LeaveAreaLUA("AR3001","",[2238.1108],NE))
	ActionOverride(Player4,LeaveAreaLUA("AR3001","",[2202.1075],NE))
	ActionOverride(Player5,LeaveAreaLUA("AR3001","",[2170.1095],NE))
	ActionOverride(Player6,LeaveAreaLUA("AR3001","",[2191.1132],NE))
END

IF
	Global("px105wn","GLOBAL",1)
	Global("pxdgolem","GLOBAL",3)
THEN
	RESPONSE #100
	SetGlobal("px105wn","GLOBAL",2)
	ActionOverride(Player1,LeaveAreaLUA("AR5500","",[3662.1637],N))
	ActionOverride(Player2,LeaveAreaLUA("AR5500","",[3704.1627],N))
	ActionOverride(Player3,LeaveAreaLUA("AR5500","",[3702.1660],N))
	ActionOverride(Player4,LeaveAreaLUA("AR5500","",[3659.1667],N))
	ActionOverride(Player5,LeaveAreaLUA("AR5500","",[3660.1705],N))
	ActionOverride(Player6,LeaveAreaLUA("AR5500","",[3704.1700],N))
END