IF
	OnCreation()
THEN
	RESPONSE #100
		StartTimer(6,24)
		SetGlobal("difficult","PXD110",1)
	RESPONSE #100
		StartTimer(6,30)
		SetGlobal("difficult","PXD110",1)
	RESPONSE #100
		StartTimer(6,36)
		SetGlobal("difficult","PXD110",1)
	RESPONSE #100
		StartTimer(6,42)
		SetGlobal("difficult","PXD110",1)
END

IF
	Global("difficult","PXD110",1)
THEN
	RESPONSE #100
	CreateCreature("px110df",[1245.1073],SW)
	CreateCreature("px110df",[2095.1285],SW)
	CreateCreature("px110df",[3362.1291],SW)
	CreateCreature("px110df",[3044.1783],W)
	CreateCreature("px110df",[3531.2260],NW)
	CreateCreature("px110df",[2415.216],N)
	CreateCreature("px110df",[1442.2299],NE)
	CreateCreature("px110df",[659.1928],E)
	CreateCreature("px110df",[2200.1666],E)
	SetGlobal("difficult","PXD110",2)
END

IF
	GlobalGT("pxd101dead","GLOBAL",0)
	Global("pxd101nv","PXD110",0)
THEN
	RESPONSE #100
		CreateCreature("pxd110nv",[1126.1979],S)
		ContainerEnable("Container001",TRUE)
		SetGlobal("pxd101nv","PXD110",1)
END

IF
	GlobalGT("PXD110P1","GLOBAL",24)
	Global("px110nh","PXD110",0)
THEN
	RESPONSE #100
		SetGlobal("px110nh","PXD110",1)
		TriggerActivation("to1101",TRUE)
		TriggerActivation("Wall",FALSE)
		CreateCreature("pxd110nh",[1050.2053],S)
END

IF
	Global("px110nh","PXD110",2)
THEN
	RESPONSE #100
		CreateCreature("pxd110nh",[1719.1165],S)
		SetGlobal("px110nh","PXD110",1)
	RESPONSE #100
		CreateCreature("pxd110nh",[2202.1285],S)
		SetGlobal("px110nh","PXD110",1)
	RESPONSE #100
		CreateCreature("pxd110nh",[2739.1492],S)
		SetGlobal("px110nh","PXD110",1)
	RESPONSE #100
		CreateCreature("pxd110nh",[2874.1762],S)
		SetGlobal("px110nh","PXD110",1)
	RESPONSE #100
		CreateCreature("pxd110nh",[2832.2092],S)
		SetGlobal("px110nh","PXD110",1)
	RESPONSE #100
		CreateCreature("pxd110nh",[2310.2113],S)
		SetGlobal("px110nh","PXD110",1)
	RESPONSE #100
		CreateCreature("pxd110nh",[1929.2230],S)
		SetGlobal("px110nh","PXD110",1)
	RESPONSE #100
		CreateCreature("pxd110nh",[1332.2200],S)
		SetGlobal("px110nh","PXD110",1)
	RESPONSE #100
		CreateCreature("pxd110nh",[1050.2053],S)
		SetGlobal("px110nh","PXD110",1)
	RESPONSE #100
		CreateCreature("pxd110nh",[684.1798],S)
		SetGlobal("px110nh","PXD110",1)
	RESPONSE #100
		CreateCreature("pxd110nh",[2400.1021],S)
		SetGlobal("px110nh","PXD110",1)
	RESPONSE #100
		CreateCreature("pxd110nh",[1146.2332],S)
		SetGlobal("px110nh","PXD110",1)
END

IF
	TimerExpired(6)
	RandomNum(10,1)
THEN
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[2026.1462])
		CreateCreature("pxd101sp",[1719.1165],S)
		StartTimer(6,18)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[2026.1462])
		CreateCreature("pxd101sp",[2202.1285],S)
		StartTimer(6,18)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[2026.1462])
		CreateCreature("pxd101sp",[2739.1492],S)
		StartTimer(6,24)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[2026.1462])
		CreateCreature("pxd101sp",[2874.1762],S)
		StartTimer(6,24)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[2026.1462])
		CreateCreature("pxd101sp",[2832.2092],S)
		StartTimer(6,30)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[2026.1462])
		CreateCreature("pxd101sp",[2310.2113],S)
		StartTimer(6,30)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[2026.1462])
		CreateCreature("pxd101sp",[1929.2230],S)
		StartTimer(6,36)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[2026.1462])
		CreateCreature("pxd101sp",[1332.2200],S)
		StartTimer(6,36)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[2026.1462])
		CreateCreature("pxd101sp",[1050.2053],S)
		StartTimer(6,42)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[2026.1462])
		CreateCreature("pxd101sp",[684.1798],S)
		StartTimer(6,42)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[2026.1462])
		CreateCreature("pxd101sp",[2400.1021],S)
		StartTimer(6,48)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[2026.1462])
		CreateCreature("pxd101sp",[1146.2332],S)
		StartTimer(6,48)
END

IF
	TimerExpired(6)
THEN
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[2026.1462])
		StartTimer(6,18)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[2026.1462])
		StartTimer(6,24)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[2026.1462])
		StartTimer(6,30)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[2026.1462])
		StartTimer(6,36)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[2026.1462])
		StartTimer(6,42)
	RESPONSE #100
		ReallyForceSpellPointRES("Pxd1101",[2026.1462])
		StartTimer(6,48)
END

IF
    Global("px110wn","GLOBAL",1)
	Global("pxdgolem","GLOBAL",1)
THEN
    RESPONSE #100
    SetGlobal("px110wn","GLOBAL",2)
    ActionOverride(Player1,LeaveAreaLUA("AR0500","",[2387.1252],NNW))
    ActionOverride(Player2,LeaveAreaLUA("AR0500","",[2428.1222],NNW))
    ActionOverride(Player3,LeaveAreaLUA("AR0500","",[2477.1247],NNW))
    ActionOverride(Player4,LeaveAreaLUA("AR0500","",[2437.1281],NNW))
    ActionOverride(Player5,LeaveAreaLUA("AR0500","",[2484.1249],NNW))
    ActionOverride(Player6,LeaveAreaLUA("AR0500","",[2520.1270],NNW))
END


IF
	Global("px110wn","GLOBAL",1)
	Global("pxdgolem","GLOBAL",2)
THEN
	RESPONSE #100
	SetGlobal("px110wn","GLOBAL",2)
	ActionOverride(Player1,LeaveAreaLUA("AR3001","",[2253.1042],NE))
	ActionOverride(Player2,LeaveAreaLUA("AR3001","",[2280.1074],NE))
	ActionOverride(Player3,LeaveAreaLUA("AR3001","",[2238.1108],NE))
	ActionOverride(Player4,LeaveAreaLUA("AR3001","",[2202.1075],NE))
	ActionOverride(Player5,LeaveAreaLUA("AR3001","",[2170.1095],NE))
	ActionOverride(Player6,LeaveAreaLUA("AR3001","",[2191.1132],NE))
END


IF
	Global("px110wn","GLOBAL",1)
	Global("pxdgolem","GLOBAL",3)
THEN
	RESPONSE #100
	SetGlobal("px110wn","GLOBAL",2)
	ActionOverride(Player1,LeaveAreaLUA("AR5500","",[3662.1637],N))
	ActionOverride(Player2,LeaveAreaLUA("AR5500","",[3704.1627],N))
	ActionOverride(Player3,LeaveAreaLUA("AR5500","",[3702.1660],N))
	ActionOverride(Player4,LeaveAreaLUA("AR5500","",[3659.1667],N))
	ActionOverride(Player5,LeaveAreaLUA("AR5500","",[3660.1705],N))
	ActionOverride(Player6,LeaveAreaLUA("AR5500","",[3704.1700],N))
END