IF
	OnCreation()
THEN
	RESPONSE #100
		StartTimer(30,30)
		GiveItemCreate("Pxdvoid","pxd108b",0,0,0)
	RESPONSE #100
		StartTimer(30,30)
		GiveItemCreate("pxdvoid","pxd160b",0,0,0)
	RESPONSE #100
		StartTimer(30,30)
		GiveItemCreate("Pxdvoid","pxd610b",0,0,0)
	RESPONSE #100
		StartTimer(30,30)
		GiveItemCreate("Pxdvoid","pxd208b",0,0,0)
	RESPONSE #100
		StartTimer(30,30)
		GiveItemCreate("Pxdvoid","pxd180b",0,0,0)
	RESPONSE #100
		StartTimer(30,30)
		GiveItemCreate("Pxdvoid","pxd100b",0,0,0)
	RESPONSE #100
		StartTimer(30,30)
		SetGlobal("PXD204P","PXD204",1)
END

IF
	Global("pxd204b","GLOBAL",1)
THEN
	RESPONSE #100
	DisplayStringHead(Player1,@143)
	SetGlobal("pxd204b","GLOBAL",2)
END

IF
	GlobalGT("pxd208b","GLOBAL",3)
THEN
	RESPONSE #100
		CreateCreature("px208c",[1750.1063],W)
		SetGlobal("pxd208b","GLOBAL",0)
END

IF
	TimerExpired(30)
	Global("PXD204l","PXD204",0)
THEN
	RESPONSE #100
		CreateCreature("px201c",[1446.864],W)
		StartTimer(35,35)
		SetGlobal("PXD204l","PXD204",1)
END

IF
	Global("PXD204l","PXD204",1)
	Global("PXD204P","PXD204",1)
THEN
	RESPONSE #100	
	GiveItemCreate("Pxdvoid","pxd201b",0,0,0)
	SetGlobal("PXD204P","PXD204",1)
END

IF
	TimerExpired(35)
	Global("PXD2042","PXD204",0)
THEN
	RESPONSE #100
		CreateCreature("px101c",[1435.864],W)
		ReallyForceSpellPointRES("px101bn",[1356.973])
		ReallyForceSpellPointRES("px101be",[1260.864])
		ReallyForceSpellPointRES("px101bb",[1317.749])
		ReallyForceSpellPointRES("px101bp",[1439.730])
		ReallyForceSpellPointRES("px101bv",[1591.773]) 
		ReallyForceSpellPointRES("px101bg",[1634.8686])
		ReallyForceSpellPointRES("px101bm",[1640.953])
		ReallyForceSpellPointRES("px101ba",[1502.1014])
		ActionOverride("pxd101c",StartDialogueNoSet([PC]))
		SetGlobal("PXD2042","PXD204",1)
END

IF
	GlobalGT("pxdvoid","GLOBAL",0)
THEN
	RESPONSE #100
		ClearAllActions()
		StorePartyLocations()
		CreateVisualEffectObject("icccmdsi",Player1)
		CreateVisualEffectObject("icccmdsi",Player2)
		CreateVisualEffectObject("icccmdsi",Player3)
		CreateVisualEffectObject("icccmdsi",Player4)
		CreateVisualEffectObject("icccmdsi",Player5)
		CreateVisualEffectObject("icccmdsi",Player6)
		CreateVisualEffectObject("icccmdsi",Familiar)
		Wait(2)
		ActionOverride(Player1,LeaveAreaLUA("PXD105","",[756.1939],SE))
		ActionOverride(Player2,LeaveAreaLUA("PXD105","",[723.2008],SE))
		ActionOverride(Player3,LeaveAreaLUA("PXD105","",[689.1977],SE))
		ActionOverride(Player4,LeaveAreaLUA("PXD105","",[719.1943],SE))
		ActionOverride(Player5,LeaveAreaLUA("PXD105","",[677.1916],SE))
		ActionOverride(Player6,LeaveAreaLUA("PXD105","",[647.1947],SE))
		SetGlobal("pxdvoid","GLOBAL",0)
END