/////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////   BASES DU MODULE   ////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////

SILENT
INCLUDE ~Derats_Defis/Base/Codes.tpa~
LAM ~GW_ADJUST_COL_TOOLTIP~
LAM ~GW_READ_COL_TOOLTIP~
INCLUDE ~Derats_Defis/Scripts/Installs/Base.tph~
VERBOSE



/////////////////////////////////////////////////////////////////////////////////////
/////////////////////////   108 - LA DECHARGE + 404 + 903   /////////////////////////
/////////////////////////////////////////////////////////////////////////////////////

PRINT  @121
SILENT
INCLUDE ~Derats_Defis/Scripts/Installs/Pxd108.tph~
VERBOSE

/////////////////////////////////////////////////////////////////////////////////////
//////////////////////   160 - LA NÉCROPOLE SILENCIEUSE + 150  //////////////////////
/////////////////////////////////////////////////////////////////////////////////////

PRINT  @122
SILENT
INCLUDE ~Derats_Defis/Scripts/Installs/Pxd160.tph~
VERBOSE

/////////////////////////////////////////////////////////////////////////////////////
////////////////////////////   610 - LE JARDIN VEGETAL   ////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////

PRINT  @123
SILENT
INCLUDE ~Derats_Defis/Scripts/Installs/Pxd610.tph~
VERBOSE

/////////////////////////////////////////////////////////////////////////////////////
///////////////////////////   208 - LES TOMBEAUX D'ACIER   //////////////////////////
/////////////////////////////////////////////////////////////////////////////////////

PRINT  @124
SILENT
INCLUDE ~Derats_Defis/Scripts/Installs/Pxd208.tph~
VERBOSE

/////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////   190 - LE DÉDALE   ////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////

PRINT  @125
SILENT
INCLUDE ~Derats_Defis/Scripts/Installs/Pxd190.tph~
VERBOSE

/////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////   180 - ANTIMAGINIUM   //////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////

PRINT  @126
SILENT
INCLUDE ~Derats_Defis/Scripts/Installs/Pxd180.tph~
VERBOSE

/////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////   100 - LA FOURNAISE   //////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////
PRINT  @127
SILENT
INCLUDE ~Derats_Defis/Scripts/Installs/Pxd100.tph~
VERBOSE

/*
/////////////////////////////////////////////////////////////////////////////////////
//////////////////////   110 - LE TOMBEAU DU GRAND VER + 101   //////////////////////
/////////////////////////////////////////////////////////////////////////////////////
PRINT  @128
SILENT
COPY ~Derats_Defis/pxd110/Area~					~override~
COPY ~Derats_Defis/pxd110/Anim/Abishai-red-blue~ ~override~
COPY ~Derats_Defis/pxd110/Anim/Half-dragon_black~ ~override~
COPY ~Derats_Defis/pxd110/Anim/Half-dragon_red~	~override~
COPY_EXISTING ~pxd108sp.cre~		~override/pxd110sp.cre~	WRITE_ASCII 0x514 ~pxd110sp~ #8
COPY_EXISTING ~pxd108sp.spl~		~override/pxd110sp.spl~	WRITE_ASCII 0xae ~pxd110~ #8



COPY ~Derats_Defis/pxd110/pxd101/Area~			~override~
COPY ~Derats_Defis/pxd110/items/pxdbatoc.itm~ 	~override~	SAY NAME2 @251	SAY DESC @252

VERBOSE

/////////////////////////////////////////////////////////////////////////////////////
//////////////////////////   201 - LA SALLE DE JEU DU MAL   /////////////////////////
/////////////////////////////////////////////////////////////////////////////////////
PRINT  @129
SILENT
COPY ~Derats_Defis/pxd201/Area~					~override~
COPY_EXISTING ~pxd108sp.cre~		~override/pxd201sp.cre~	WRITE_ASCII 0x514 ~pxd201sp~ #8
COPY_EXISTING ~pxd108sp.spl~		~override/pxd201sp.spl~	WRITE_ASCII 0xae ~pxd201~ #8


VERBOSE

*/

/////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////   708 - LA FORGE + 501   /////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////
PRINT  @130
SILENT
INCLUDE ~Derats_Defis/Scripts/Installs/Pxd708.tph~
VERBOSE
/*

/////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////   105 - LA BIBLIOTHÈQUE   /////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////
PRINT  @132
SILENT
COPY ~Derats_Defis/pxd105/Area~					~override~
COPY ~Derats_Defis/pxd105/Copy~					~override~

////Nouvelle animation : Tarasque
LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7000 slotMax = 0xefff RET slot END
ACTION_IF (slot <= 0) BEGIN
  FAIL ~No free creature animation slot found.~
END

LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
APPEND ~animate.ids~ ~0x%hexNumber% GW_Tarasque~ UNLESS ~GW_Tarasque~
CLEAR_IDS_MAP

COPY ~Derats_Defis/pxd105/Anim/xdr1.ini~ ~override/%hexNumber%.ini~
ACTION_BASH_FOR ~Derats_Defis/pxd105/Anim/Tarasque~ ~^.+\.bam$~ BEGIN
  COPY ~%BASH_FOR_FILESPEC%~ ~override~
END

////items
COPY ~Derats_Defis/pxd105/items/pxdnegac.itm~	~override~	SAY NAME2 @235	SAY DESC @236
COPY_EXISTING ~spwi403d.eff~		~override/pxdnegac.eff~	WRITE_ASCII 0x30 ~pxdnegac~ #8

VERBOSE

/////////////////////////////////////////////////////////////////////////////////////
/////////////////////////   200 - LA GALERIE DE L'AGONIE   //////////////////////////
/////////////////////////////////////////////////////////////////////////////////////
SILENT


////Nouvelle animation : Élémentaire de pierre de Diablo2
LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7F00 slotMax = 0xefff RET slot END
ACTION_IF (slot <= 0) BEGIN
  FAIL ~No free creature animation slot found.~
END

LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
APPEND ~animate.ids~ ~0x%hexNumber% D2_Stone_elemental~ UNLESS ~D2_Stone_elemental~
CLEAR_IDS_MAP

COPY ~Derats_Defis/pxd105/items/Discombulateur/Blob1/Anim/pxdg.ini~ ~override/%hexNumber%.ini~
ACTION_BASH_FOR ~Derats_Defis/Secrets/blob1/Anim/Skins_Stone_Elemental~ ~^.+\.bam$~ BEGIN
  COPY ~%BASH_FOR_FILESPEC%~ ~override~
END


COPY ~Derats_Defis/pxd105/items/Discombulateur/Blob1/copy~	~override~
COPY ~Derats_Defis/pxd105/items/Discombulateur/Blob1/area~	~override~
COPY_EXISTING ~pxd108sp.cre~		~override/pxd200sp.cre~	WRITE_ASCII 0x514 ~pxd200sp~ #8
COPY_EXISTING ~pxd108sp.spl~		~override/pxd200sp.spl~	WRITE_ASCII 0xae ~pxd200~ #8




/////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////  290 - LE PÂTURAGE   ////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////


////Nouvelle animation : Minotaure en armure de Diablo2
LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
ACTION_IF (slot <= 0) BEGIN
  FAIL ~No free creature animation slot found.~
END

LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
APPEND ~animate.ids~ ~0x%hexNumber% D2_Minotaur~ UNLESS ~D2_Minotaur~
CLEAR_IDS_MAP

COPY ~Derats_Defis/pxd105/items/Discombulateur/Blob2/Anim/skmn.ini~ ~override/%hexNumber%.ini~
ACTION_BASH_FOR ~Derats_Defis/pxd105/items/Discombulateur/Blob2/Anim/Skins_Minotaure~ ~^.+\.bam$~ BEGIN
  COPY ~%BASH_FOR_FILESPEC%~ ~override~
END

////Nouvelle animation : Vache avec hallebarde de Diablo2
LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
ACTION_IF (slot <= 0) BEGIN
  FAIL ~No free creature animation slot found.~
END

LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
ACTION_IF (slot <= 0) BEGIN
  FAIL ~No free creature animation slot found.~
END

LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
APPEND ~animate.ids~ ~0x%hexNumber% bovine_axe_thing~ UNLESS ~bovine_axe_thing~
CLEAR_IDS_MAP

COPY ~Derats_Defis/pxd105/items/Discombulateur/Blob2/Anim/d2cow.ini~ ~override/%hexNumber%.ini~
ACTION_BASH_FOR ~Derats_Defis/pxd105/items/Discombulateur/Blob2/Anim/Anim/bovine_axe_thing~ ~^.+\.bam$~ BEGIN
  COPY ~%BASH_FOR_FILESPEC%~ ~override~
END

LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
ACTION_IF (slot <= 0) BEGIN
  FAIL ~No free creature animation slot found.~
END


COPY ~Derats_Defis/pxd105/items/Discombulateur/Blob2/copy~	~override~
COPY ~Derats_Defis/pxd105/items/Discombulateur/Blob2/area~	~override~
COPY_EXISTING ~pxd108sp.cre~		~override/pxd290sp.cre~	WRITE_ASCII 0x514 ~pxd290sp~ #8
COPY_EXISTING ~pxd108sp.spl~		~override/pxd290sp.spl~	WRITE_ASCII 0xae ~pxd290~ #8

ADD_PROJECTILE	~Derats_Defis/pxd105/items/Discombulateur/Blob2/pxdcowbl.pro~				~pxd proximity Cow~
COPY ~Derats_Defis/pxd105/items/Discombulateur/Blob2/pxdcowbl.spl~	~override~	WRITE_SHORT 0x98 ~%pxdcowbl%~
COPY_EXISTING	~amcall.vvc~		~override/pxfycalv.vvc~	WRITE_ASCII 0x8 ~pxfycal2~ #8	WRITE_ASCII 0x78 ~pxfycalo~ #8


VERBOSE

*/


PRINT  @119
SILENT
COMPILE ~Derats_Defis/Scripts~
COMPILE ~Derats_Defis/Temp~
COMPILE ~Derats_Defis/Dialogs~

DEFINE_PATCH_FUNCTION Antiall BEGIN
LPF Anti108 END
LPF Anti160 END
LPF Anti610 END
LPF Anti208 END
LPF Anti190 END
LPF Anti180 END
LPF Anti100 END
END
COPY_EXISTING ~zombie01.cre~		~override/pxdnecr1.cre~
			  ~skelet01.cre~		~override/pxdnecr2.cre~
			  ~skelwa02.cre~		~override/pxdnecr3.cre~
			  ~ghoul01.cre~			~override/pxdnecr4.cre~LPF Antiall END	LPF Anticre END	
			  LPF ADD_CRE_EFFECT INT_VAR opcode = 16 target = 1 timing = 9  END
VERBOSE
